package studyreport.fodmap;

public enum FodmapCSVDecription {
    numero_d_identification(0, FodmapAnswer.ID, new FodmapGroup[]{}),
    diet_1(1, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_2(2, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_3(3, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_4(4, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_5(5, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_6(6, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_7(7, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_8(8, FodmapAnswer.DIET, new FodmapGroup[]{}),
    diet_food_999_a(9, FodmapAnswer.OTHER, new FodmapGroup[]{}),
    diet_food_999_b(0, FodmapAnswer.OTHER, new FodmapGroup[]{}),
    diet_food_a_001(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_002(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_003(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_004(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_005(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_006(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_007(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_008(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_009(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_010(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_011(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_012(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_013(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_014(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_015(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_016(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_017(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_018(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_019(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_020(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_021(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_022(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_023(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_024(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_025(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_026(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_027(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_028(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_029(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_030(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_031(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_032(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_033(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_034(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_035(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_036(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_037(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_038(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_039(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_040(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_041(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_042(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_043(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_044(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_045(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_046(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_047(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_048(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_049(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_050(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_051(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_052(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_053(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_054(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_055(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_056(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_057(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_058(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_059(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_060(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_061(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_062(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_063(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_064(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_065(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_066(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_067(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_068(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_069(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_070(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_071(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_072(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_073(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_074(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_075(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_076(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_077(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_078(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_079(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_080(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_081(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_082(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_083(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_084(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_085(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_086(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_087(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_088(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_089(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_090(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_091(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_092(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_093(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_094(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_095(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_096(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_097(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_098(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_099(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_100(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_101(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_102(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES}),
    diet_food_a_103(0, FodmapAnswer.FOOD, new FodmapGroup[]{FodmapGroup.FRUCTANES});

    private final int columnId;
    private final FodmapAnswer type; //freeText, DietFood, ?
    private final FodmapGroup[] groups;
//    private final String frenchTranslation;


    FodmapCSVDecription(int columnId, FodmapAnswer type, FodmapGroup[] groups) {
        this.columnId = columnId;
        this.type = type;
        this.groups = groups;
    }
}
